# Data Manipulation Studio

For this studio, we will revisit the data set from our last studio. If you recall, California farmers were looking for advice on growing pumpkins. We will use the same [pumpkins dataset](https://www.kaggle.com/usda/a-year-of-pumpkin-prices) as provided by the U.S. Department of Agriculture. You may have to clean data in the process of data manipulation, so feel free to pull up your notebook from the last class's studio.

We will now be focusing our attention on a different region in the United States, the Northeast. When you open up the `dataset` folder, you will have 13 CSVs, including the San Francisco and Los Angeles data from the last lesson. The 13 CSVs are each a different terminal market in the United States.

A **terminal market** is a central site, often in a metropolitan area, that serves as an assembly and trading place for commodities. Terminal markets for agricultural commodities are usually at or near major transportation hubs. [Definition Source](https://en.wikipedia.org/wiki/Terminal_market#:~:text=A%20terminal%20market%20is%20a,or%20near%20major%20transportation%20hubs)

## Getting Started

Import the CSVs for each of the following cities: Baltimore, Boston, New York, and Philadelphia. Set up a dataframe for each city.

In [83]:
# Import the necessary libraries and CSVs. Make some dataframes!
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

Baltimore=pd.read_csv("baltimore_9-24-2016_9-30-2017.csv")
Boston=pd.read_csv("boston_9-24-2016_9-30-2017.csv")
New_York=pd.read_csv("new-york_9-24-2016_9-30-2017.csv")
Philadelphia=pd.read_csv("philadelphia_9-24-2016_9-30-2017.csv")

## Clean Your Data

In the last lesson, we cleaned the data related to San Francisco. Pull up your notebook from the last lesson and use it as a reference to clean up these new dataframes.

In [84]:
# Clean your data here!
Baltimore.drop_duplicates()
Boston.drop_duplicates()
New_York.drop_duplicates()
Philadelphia.drop_duplicates()

Baltimore["Type"] = Baltimore["Type"].fillna("Conventional")
Boston["Type"] = Boston["Type"].fillna("Conventional")
New_York["Type"] = New_York["Type"].fillna("Conventional")
Philadelphia["Type"] = Philadelphia["Type"].fillna("Conventional")

Baltimore = Baltimore.drop(["Grade"], axis=1)
Boston = Boston.drop(["Grade"], axis=1)
New_York = New_York.drop(["Grade"], axis=1)
Philadephia = Philadelphia.drop(["Grade"], axis=1)

In [85]:
Baltimore = Baltimore.drop(["Origin District", "Origin District", "Environment", "Quality", "Condition", "Appearance", "Trans Mode", "Storage", "Crop", "Color", "Sub Variety"], axis=1)
Boston = Boston.drop(["Origin District", "Origin District", "Environment", "Quality", "Condition", "Appearance", "Trans Mode", "Storage", "Crop", "Color", "Sub Variety"], axis=1)
New_York = New_York.drop(["Origin District", "Origin District", "Environment", "Quality", "Condition", "Appearance", "Trans Mode", "Storage", "Crop", "Color", "Sub Variety"], axis=1)
Philadelphia = Philadelphia.drop(["Origin District", "Origin District", "Environment", "Quality", "Condition", "Appearance", "Trans Mode", "Storage", "Crop", "Color", "Sub Variety", "Grade"], axis=1)

In [86]:
Baltimore["Origin"] = Baltimore["Origin"].fillna("Unknown")
Boston["Origin"] = Boston["Origin"].fillna("Unknown")
New_York["Origin"] = New_York["Origin"].fillna("Unknown")
Philadelphia["Origin"] = Philadelphia["Origin"].fillna("Unknown")

In [87]:
Baltimore["High Price"]=Baltimore["High Price"].astype(int)
Baltimore["Mostly High"]=Baltimore["Mostly High"].astype(int)

In [88]:
Baltimore.head()

,Commodity Name,City Name,Type,Package,Variety,Date,Low Price,High Price,Mostly Low,Mostly High,Origin,Item Size,Unit of Sale,Repack
0,PUMPKINS,BALTIMORE,Conventional,24 inch bins,NaN,04/29/2017,270,280,270,280,Unknown,lge,NaN,E
1,PUMPKINS,BALTIMORE,Conventional,24 inch bins,NaN,05/06/2017,270,280,270,280,Unknown,lge,NaN,E
2,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,09/24/2016,160,160,160,160,DELAWARE,med,NaN,N
3,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,09/24/2016,160,160,160,160,VIRGINIA,med,NaN,N
4,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,11/05/2016,90,100,90,100,MARYLAND,lge,NaN,N

## Combine Your Data

Now that you have four clean sets of data, combine all four into one dataframe that represents the entire Northeast region.

In [89]:
# Combine the four dataframes into one!
Northeast=Baltimore.merge(Boston, how="outer").merge(New_York, how="outer").merge(Philadelphia, how="outer")
Northeast.sample(5)

,Commodity Name,City Name,Type,Package,Variety,Date,Low Price,High Price,Mostly Low,Mostly High,Origin,Item Size,Unit of Sale,Repack
403,PUMPKINS,BOSTON,Conventional,36 inch bins,HOWDEN TYPE,10/22/2016,160,180,160,160,CANADA,lge,NaN,N
537,PUMPKINS,NEW YORK,Conventional,1/2 bushel cartons,MINIATURE,11/05/2016,18,18,18,18,OHIO,sml,NaN,N
32,PUMPKINS,BALTIMORE,Conventional,1/2 bushel cartons,MINIATURE,10/01/2016,15,15,15,15,MARYLAND,sml,NaN,N
112,PUMPKINS,BALTIMORE,Conventional,24 inch bins,HOWDEN TYPE,11/12/2016,90,100,90,100,MARYLAND,lge,NaN,N
244,PUMPKINS,BOSTON,Conventional,24 inch bins,FAIRYTALE,10/08/2016,260,285,285,285,MASSACHUSETTS,xlge,NaN,N

## Answer Some Questions

Use `groupby()` and `agg()` to answer the following two questions:

1. What is the mean low and high prices for each type of **unit of sale** in the Northeast region? 
2. For each region, what is the average number of pumpkins per variety that came into terminal markets for the year?

In [ ]:
# Put your code here to find the mean low and high prices in the Northeast region for each type of unit of sale.
Northeast.groupby("Unit of Sale").mean(numeric_only=True)

               Low Price  High Price  Mostly Low  Mostly High
Unit of Sale
EACH           47.916667   59.166667   47.916667    59.166667
PER BIN       185.845070  206.619718  193.521127   204.859155
SHELLACKED     16.000000   17.545455   16.000000    17.545455

In [97]:
# Put your code here to find the average number of pumpkins coming into terminal markets of each variety.
Northeast.groupby("Variety")["City Name"].count()

Variety
BIG MACK TYPE                55
BLUE TYPE                     7
CINDERELLA                   39
FAIRYTALE                    37
HOWDEN TYPE                 224
HOWDEN WHITE TYPE             2
KNUCKLE HEAD                  9
MINIATURE                    97
MIXED HEIRLOOM VARIETIES      4
PIE TYPE                    198
Name: City Name, dtype: int64

## Bonus Mission

Try answering the same questions for the Midwest (Chicago, Detroit, and St. Louis) or the Southeast (Atlanta, Columbia, and Miami) regions.

In [59]:
# Try the bonus mission if you have time!