Importing applications and csvs

In [35]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np
customers=pd.read_csv("customers.csv")
orders=pd.read_csv("orders.csv")
order_items=pd.read_csv("order_items.csv")

Sort the last name column alphabetically

In [36]:
customers.sort_values("last_name").head()

     customer_id first_name last_name      city
31          1032       Noah     Brown        LA
112         1113      Maria     Brown       NYC
97          1098        Zoe      Chen        LA
53          1054        Zoe     Davis  New York
32          1033       alex     Davis   chicago

Sort the order date descending order

In [37]:
orders.sort_values("order_date",ascending=False)

     order_id  customer_id  order_date
213      5214         1075  2024-03-31
383      5384         1111  2024-03-31
215      5216         1103  2024-03-31
207      5208         1023  2024-03-30
14       5015         1019  2024-03-30
..        ...          ...         ...
430      5431         1006  2024-01-01
271      5272         1004  2024-01-01
56       5057         1019  2024-01-01
13       5014         1090  2024-01-01
246      5247         1017  2024-01-01

[450 rows x 3 columns]

Filter the order items dataset to only show rows where quantity of items is 2 or higher. AND sort by quantity.

In [38]:
over_two=order_items[order_items["quantity"]>=2].sort_values("quantity")
print(over_two)

     order_id product_name  quantity  unit_price
870      5450      Monitor         2         300
26       5199      Monitor         2         300
22       5047        Mouse         2          25
17       5143      Monitor         2         300
16       5268    USB Cable         2          10
..        ...          ...       ...         ...
54       5108       Laptop         3        1200
42       5215    Desk Lamp         3          45
40       5328      Monitor         3         300
32       5391        Mouse         3          25
31       5250      Monitor         3         300

[464 rows x 4 columns]

Clean up the first & last name columns (remove leading spaces and capitalize them all)

In [39]:
customers["first_name"]=customers["first_name"].str.strip().str.capitalize()
customers["last_name"]=customers["last_name"].str.strip().str.capitalize()

In [40]:
customers.sort_values("last_name")

     customer_id first_name last_name         city
12          1013      Priya  Anderson           LA
113         1114      Maria  Anderson           LA
81          1082     Jordan  Anderson      chicago
109         1110      Maria  Anderson           LA
4           1005      Priya  Anderson           LA
..           ...        ...       ...          ...
68          1069     Taylor    Wilson          NYC
71          1072     Taylor    Wilson           LA
95          1096        Zoe    Wilson  Los Angeles
40          1041       Evan    Wilson  Los Angeles
59          1060     Jordan    Wilson          NYC

[120 rows x 4 columns]

Look up all the different values in a given column--in this case, the city column, so we can clean up.

In [41]:
customers["city"].value_counts()

#OR

customers["city"].unique()

array(['New York', 'chicago', 'Los Angeles', 'new york', 'LA', 'NYC',
       'Chicago'], dtype=object)

Create a dictionary of values to be replaced/what to replace them with.

In [51]:
city_standardization= {'LA' : 'Los Angeles', 
                       'NYC' : 'New York'}
customers["city"]=customers["city"].replace(city_standardization)
customers["city"]=customers["city"].str.title()

customers["city"].value_counts()

city
New York       52
Los Angeles    41
Chicago        27
Name: count, dtype: int64

Using .apply()

In [ ]:
customers["last_name"].value_counts()
#shows us some last names have space before them

last_name
Davis       19
Smith       18
Patel       17
Brown       16
Chen        16
Anderson    13
Wilson      13
Lopez        8
Name: count, dtype: int64

When we use lambda, it creates a quick "inline" function. Defines a function really quickly, in this case we called it function 'x'. 'x' stands for the value and we define the function on the last line. With each last name being 'x', apply this function. In this case, apply the strip function.

In [48]:
customers["clean_last_name"]= customers["last_name"].apply(
    lambda x:
    x.strip()
)
customers["clean_last_name"].value_counts()

clean_last_name
Davis       19
Smith       18
Patel       17
Brown       16
Chen        16
Anderson    13
Wilson      13
Lopez        8
Name: count, dtype: int64

Create a new column called total price (which is calculated by multiplying unit price by quantity)

In [52]:
order_items["total_price"] = order_items["quantity"]*order_items["unit_price"]
order_items

     order_id product_name  quantity  unit_price  total_price
0        5311      Monitor         3         300          900
1        5303     Keyboard         3          70          210
2        5012     Keyboard         3          70          210
3        5318      Monitor         3         300          900
4        5080    USB Cable         1          10           10
..        ...          ...       ...         ...          ...
895      5303    USB Cable         2          10           20
896      5117      Monitor         2         300          600
897      5124     Keyboard         1          70           70
898      5399    USB Cable         2          10           20
899      5281      Monitor         1         300          300

[900 rows x 5 columns]

Create new column called total_price_apply. Use .apply on each row (so to entire dataset). This does the same things as the coding above! Just another way to do it.

In [54]:
order_items["total_price_apply"] = order_items.apply(
    lambda row:
    row["quantity"]*row["unit_price"], axis=1
)
order_items

,order_id,product_name,quantity,unit_price,total_price,total_price_apply
0,5311,Monitor,3,300,900,900
1,5303,Keyboard,3,70,210,210
2,5012,Keyboard,3,70,210,210
3,5318,Monitor,3,300,900,900
4,5080,USB Cable,1,10,10,10
...,...,...,...,...,...,...
895,5303,USB Cable,2,10,20,20
896,5117,Monitor,2,300,600,600
897,5124,Keyboard,1,70,70,70
898,5399,USB Cable,2,10,20,20
899,5281,Monitor,1,300,300,300

Create a new column called order type. Use apply method on the order_items dataframe. Go through each row and run the code on it. If row's quantity is more than/equal to 3, fill the column with string "Large Expensive Order", and so forth.

In [55]:
order_items["order_type"] = order_items.apply(
    lambda row: (
        "Large Expensive Order" if row ["quantity"] >= 3 and row["unit_price"] > 50
        else "Bulk Order" if row ["quantity"] >=3
        else "Standard Order"
    ), axis=1
)
order_items

,order_id,product_name,quantity,unit_price,total_price,total_price_apply,order_type
0,5311,Monitor,3,300,900,900,Large Expensive Order
1,5303,Keyboard,3,70,210,210,Large Expensive Order
2,5012,Keyboard,3,70,210,210,Large Expensive Order
3,5318,Monitor,3,300,900,900,Large Expensive Order
4,5080,USB Cable,1,10,10,10,Standard Order
...,...,...,...,...,...,...,...
895,5303,USB Cable,2,10,20,20,Standard Order
896,5117,Monitor,2,300,600,600,Standard Order
897,5124,Keyboard,1,70,70,70,Standard Order
898,5399,USB Cable,2,10,20,20,Standard Order
899,5281,Monitor,1,300,300,300,Standard Order

Merging tables

In [56]:
orders_with_customers=orders.merge(customers,how="inner")
orders_with_customers.head()

,order_id,customer_id,order_date,first_name,last_name,city,clean_last_name
0,5001,1089,2024-01-26,Aisha,Smith,New York,Smith
1,5002,1045,2024-02-20,Priya,Davis,New York,Davis
2,5003,1004,2024-02-14,Aisha,Smith,New York,Smith
3,5004,1036,2024-02-13,Chloe,Davis,New York,Davis
4,5005,1070,2024-01-05,Jordan,Brown,Los Angeles,Brown

In [57]:
orders_customers_items=orders_with_customers.merge(order_items, on="order_id", how="inner")
orders_customers_items.head()

,order_id,customer_id,order_date,first_name,last_name,city,clean_last_name,product_name,quantity,unit_price,total_price,total_price_apply,order_type
0,5001,1089,2024-01-26,Aisha,Smith,New York,Smith,Monitor,1,300,300,300,Standard Order
1,5001,1089,2024-01-26,Aisha,Smith,New York,Smith,Desk Lamp,2,45,90,90,Standard Order
2,5001,1089,2024-01-26,Aisha,Smith,New York,Smith,Desk Lamp,1,45,45,45,Standard Order
3,5002,1045,2024-02-20,Priya,Davis,New York,Davis,Monitor,2,300,600,600,Standard Order
4,5002,1045,2024-02-20,Priya,Davis,New York,Davis,Monitor,2,300,600,600,Standard Order

In [58]:
combined= (
    orders.merge(customers, on="customer_id", how="inner").merge(order_items, on="order_id", how="inner")
)
combined

,order_id,customer_id,order_date,first_name,last_name,city,clean_last_name,product_name,quantity,unit_price,total_price,total_price_apply,order_type
0,5001,1089,2024-01-26,Aisha,Smith,New York,Smith,Monitor,1,300,300,300,Standard Order
1,5001,1089,2024-01-26,Aisha,Smith,New York,Smith,Desk Lamp,2,45,90,90,Standard Order
2,5001,1089,2024-01-26,Aisha,Smith,New York,Smith,Desk Lamp,1,45,45,45,Standard Order
3,5002,1045,2024-02-20,Priya,Davis,New York,Davis,Monitor,2,300,600,600,Standard Order
4,5002,1045,2024-02-20,Priya,Davis,New York,Davis,Monitor,2,300,600,600,Standard Order
...,...,...,...,...,...,...,...,...,...,...,...,...,...
895,5450,1008,2024-02-26,Maria,Smith,New York,Smith,Laptop,2,1200,2400,2400,Standard Order
896,5450,1008,2024-02-26,Maria,Smith,New York,Smith,Keyboard,3,70,210,210,Large Expensive Order
897,5450,1008,2024-02-26,Maria,Smith,New York,Smith,USB Cable,2,10,20,20,Standard Order
898,5450,1008,2024-02-26,Maria,Smith,New York,Smith,Mouse,3,25,75,75,Bulk Order
899,5450,1008,2024-02-26,Maria,Smith,New York,Smith,Monitor,2,300,600,600,Standard Order

Grouping and aggregation

In [59]:
order_items["total_price"].sum()

np.int64(420615)

In [60]:
order_items.groupby("product_name")["total_price"].sum()

product_name
Desk Lamp     10755
Keyboard      14140
Laptop       296400
Monitor       90000
Mouse          6750
USB Cable      2570
Name: total_price, dtype: int64

Write a line of code taht assesses the total quanity of units sold of each item, presented in descending order.

In [62]:
order_items.groupby("product_name")["quantity"].sum().sort_values(ascending=False)

product_name
Monitor      300
Mouse        270
USB Cable    257
Laptop       247
Desk Lamp    239
Keyboard     202
Name: quantity, dtype: int64

Use the agg method to group by product name and calculate the total revenue and average quantity bought. Agg is really flexible.

In [63]:
order_items.groupby("product_name").agg(
    total_revenue=("total_price", "sum"),
    avg_quantity=("quantity", "mean")
)

              total_revenue  avg_quantity
product_name
Desk Lamp             10755      1.593333
Keyboard              14140      1.578125
Laptop               296400      1.776978
Monitor               90000      1.754386
Mouse                  6750      1.719745
USB Cable              2570      1.658065

In [64]:
combined.groupby("customer_id")["total_price"].sum().sort_values(ascending=False).head()

customer_id
1008    13625
1057    13330
1087    11170
1061    10645
1070     9945
Name: total_price, dtype: int64

Reshaping dataframes: wide or long

In [71]:
sample = combined[["customer_id", "product_name", "total_price"]].head(12)

pivot=sample.pivot_table(index="customer_id", columns="product_name", values="total_price", aggfunc="sum")

pivot

product_name  Desk Lamp  Keyboard  Laptop  Monitor  Mouse  USB Cable
customer_id
1004              135.0     140.0  2400.0      NaN    NaN       20.0
1036                NaN       NaN     NaN      NaN   50.0       20.0
1045                NaN       NaN     NaN   1200.0    NaN        NaN
1089              135.0       NaN     NaN    300.0    NaN        NaN

String multiple methods together

In [ ]:
combined.query("quantity >= 2"). groupby("city").agg(
    total_revenue=("total_price", "sum")).sort_values("total_revenue", ascending = False)

             total_revenue
city
New York            131450
Los Angeles          98180
Chicago              85750